/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_deskstatus_view_control_context {
 /* add your variables here */

} uib_deskstatus_view_control_context;


void deskstatus_view_dsv_next_button_onclicked(uib_deskstatus_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function deskstatus_view_connection_deskstatus_view_dsv_next_button_onclicked

}

void deskstatus_view_dsv_next_button_onclicked_post(void* param, uib_deskstatus_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function deskstatus_view_connection_deskstatus_view_dsv_next_button_onclicked

}

void deskstatus_view_dsv_previous_button_onclicked(uib_deskstatus_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function deskstatus_view_connection_deskstatus_view_dsv_previous_button_onclicked

}

void deskstatus_view_dsv_previous_button_onclicked_post(void* param, uib_deskstatus_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function deskstatus_view_connection_deskstatus_view_dsv_previous_button_onclicked

}
