/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_datetime_view_control_context {
 /* add your variables here */

} uib_datetime_view_control_context;


void datetime_view_dtv_next_button_onclicked(uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function datetime_view_connection_datetime_view_dtv_next_button_onclicked

}

void datetime_view_dtv_next_button_onclicked_post(void* param, uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function datetime_view_connection_datetime_view_dtv_next_button_onclicked

}

void datetime_view_dtv_previous_button_onclicked(uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function datetime_view_connection_datetime_view_dtv_previous_button_onclicked

}

void datetime_view_dtv_previous_button_onclicked_post(void* param, uib_datetime_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function datetime_view_connection_datetime_view_dtv_previous_button_onclicked

}
