/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_finedust_view_control_context {
 /* add your variables here */

} uib_finedust_view_control_context;


void finedust_view_fdv_next_button_onclicked(uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function finedust_view_connection_finedust_view_fdv_next_button_onclicked

}

void finedust_view_fdv_next_button_onclicked_post(void* param, uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function finedust_view_connection_finedust_view_fdv_next_button_onclicked

}

void finedust_view_fdv_previous_button_onclicked(uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function finedust_view_connection_finedust_view_fdv_previous_button_onclicked

}

void finedust_view_fdv_previous_button_onclicked_post(void* param, uib_finedust_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function finedust_view_connection_finedust_view_fdv_previous_button_onclicked

}
